// <auto-generated />
using System;
using ConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20251031020615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp.FoodInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisCategory")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AnalysisItem")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CommonName")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentPer100g")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentPerUnit")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentPerUnitWeight")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentUnit")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataCategory")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FoodCategory")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IntegratedNumber")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SampleCount")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SampleEnglishName")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SampleName")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StandardDeviation")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnitWeight")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WasteRate")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisCategory")
                        .HasDatabaseName("IX_FoodInfos_AnalysisCategory");

                    b.HasIndex("IntegratedNumber")
                        .HasDatabaseName("IX_FoodInfos_IntegratedNumber");

                    b.HasIndex("SampleName")
                        .HasDatabaseName("IX_FoodInfos_SampleName");

                    b.ToTable("FoodInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
